// Copyright (c) 2022-2023 - for information on the respective copyright owner
// see the NOTICE file and/or the repository at
// https://github.com/catenax-ng/product-esc-backbone-code
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escbackbone/ubc/fixedbeziersegment.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FixedBezierSegment struct {
	*BezierSegment `protobuf:"bytes,1,opt,name=s,proto3,embedded=s" json:"s,omitempty"`
	IntervalP0X    github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=intervalP0X,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"intervalP0X"`
}

func (m *FixedBezierSegment) Reset()         { *m = FixedBezierSegment{} }
func (m *FixedBezierSegment) String() string { return proto.CompactTextString(m) }
func (*FixedBezierSegment) ProtoMessage()    {}
func (*FixedBezierSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd07a740e780a5d9, []int{0}
}
func (m *FixedBezierSegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FixedBezierSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FixedBezierSegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FixedBezierSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedBezierSegment.Merge(m, src)
}
func (m *FixedBezierSegment) XXX_Size() int {
	return m.Size()
}
func (m *FixedBezierSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedBezierSegment.DiscardUnknown(m)
}

var xxx_messageInfo_FixedBezierSegment proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FixedBezierSegment)(nil), "escbackbone.ubc.FixedBezierSegment")
}

func init() {
	proto.RegisterFile("escbackbone/ubc/fixedbeziersegment.proto", fileDescriptor_bd07a740e780a5d9)
}

var fileDescriptor_bd07a740e780a5d9 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x2d, 0x4e, 0x4e,
	0x4a, 0x4c, 0xce, 0x4e, 0xca, 0xcf, 0x4b, 0xd5, 0x2f, 0x4d, 0x4a, 0xd6, 0x4f, 0xcb, 0xac, 0x48,
	0x4d, 0x49, 0x4a, 0xad, 0xca, 0x4c, 0x2d, 0x2a, 0x4e, 0x4d, 0xcf, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x47, 0x52, 0xa9, 0x57, 0x9a, 0x94, 0x2c, 0xa5, 0x8c, 0xae,
	0x15, 0x8b, 0x2e, 0x29, 0x91, 0xf4, 0xfc, 0xf4, 0x7c, 0x30, 0x53, 0x1f, 0xc4, 0x82, 0x88, 0x2a,
	0xcd, 0x62, 0xe4, 0x12, 0x72, 0x03, 0x59, 0xe4, 0x04, 0xd6, 0x12, 0x0c, 0xd1, 0x22, 0x64, 0xc4,
	0xc5, 0x58, 0x2c, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0xa7, 0x87, 0x66, 0x9d, 0x1e, 0x8a,
	0x52, 0x27, 0x96, 0x0b, 0xf7, 0xe4, 0x19, 0x83, 0x18, 0x8b, 0x85, 0x02, 0xb8, 0xb8, 0x33, 0xf3,
	0x4a, 0x52, 0x8b, 0xca, 0x12, 0x73, 0x02, 0x0c, 0x22, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x9d,
	0xf4, 0x4e, 0xdc, 0x93, 0x67, 0xb8, 0x75, 0x4f, 0x5e, 0x2d, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49,
	0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x39, 0xbf, 0x38, 0x37, 0xbf, 0x18, 0x4a, 0xe9, 0x16, 0xa7, 0x64,
	0xeb, 0x97, 0x54, 0x16, 0xa4, 0x16, 0xeb, 0xb9, 0xa4, 0x26, 0x07, 0x21, 0x1b, 0xe1, 0xe4, 0x7e,
	0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7,
	0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0xba, 0xc8, 0xc6, 0x25, 0x96, 0xa4,
	0xe6, 0x25, 0x56, 0xe8, 0xa7, 0x16, 0x27, 0xeb, 0xc2, 0x43, 0xa1, 0x02, 0x14, 0x0e, 0xb9, 0xb9,
	0x10, 0x93, 0x93, 0xd8, 0xc0, 0x9e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x76, 0x5e, 0xfa,
	0xe0, 0x64, 0x01, 0x00, 0x00,
}

func (m *FixedBezierSegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FixedBezierSegment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FixedBezierSegment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.IntervalP0X.Size()
		i -= size
		if _, err := m.IntervalP0X.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFixedbeziersegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.BezierSegment != nil {
		{
			size, err := m.BezierSegment.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFixedbeziersegment(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFixedbeziersegment(dAtA []byte, offset int, v uint64) int {
	offset -= sovFixedbeziersegment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FixedBezierSegment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BezierSegment != nil {
		l = m.BezierSegment.Size()
		n += 1 + l + sovFixedbeziersegment(uint64(l))
	}
	l = m.IntervalP0X.Size()
	n += 1 + l + sovFixedbeziersegment(uint64(l))
	return n
}

func sovFixedbeziersegment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFixedbeziersegment(x uint64) (n int) {
	return sovFixedbeziersegment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FixedBezierSegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFixedbeziersegment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FixedBezierSegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FixedBezierSegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BezierSegment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFixedbeziersegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFixedbeziersegment
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFixedbeziersegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BezierSegment == nil {
				m.BezierSegment = &BezierSegment{}
			}
			if err := m.BezierSegment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntervalP0X", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFixedbeziersegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFixedbeziersegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFixedbeziersegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IntervalP0X.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFixedbeziersegment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFixedbeziersegment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFixedbeziersegment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFixedbeziersegment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFixedbeziersegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFixedbeziersegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFixedbeziersegment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFixedbeziersegment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFixedbeziersegment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFixedbeziersegment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFixedbeziersegment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFixedbeziersegment = fmt.Errorf("proto: unexpected end of group")
)
