// Copyright (c) 2022-2023 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License, Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escbackbone/ubcmm/quadraticsegment.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FixedQuadraticSegment represents a quadratic curve defined by the equation
// ax^2 + bx + c with a fixed shape and left half bounded interval.
//
// The curve parameters set during initialization will remain fixed. During
// shift up and undergird operations, only the x-interval will be modified.
//
// initialX0 is the lower bound during initialization and currentX0 is the
// lower bound of modified x-interval.
//
// The x-axis operates on a much larger values than y-axis. So, in order to
// avoid extremly small slopes, a scaling factor is used for the x-values.
type FixedQuadraticSegment struct {
	A             github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=a,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"a"`
	B             github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=b,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"b"`
	C             github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=c,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"c"`
	ScalingFactor github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=scalingFactor,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"scalingFactor"`
	InitialX0     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=initialX0,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"initialX0"`
	CurrentX0     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=currentX0,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"currentX0"`
}

func (m *FixedQuadraticSegment) Reset()         { *m = FixedQuadraticSegment{} }
func (m *FixedQuadraticSegment) String() string { return proto.CompactTextString(m) }
func (*FixedQuadraticSegment) ProtoMessage()    {}
func (*FixedQuadraticSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3b24765d5e913e2, []int{0}
}
func (m *FixedQuadraticSegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FixedQuadraticSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FixedQuadraticSegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FixedQuadraticSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedQuadraticSegment.Merge(m, src)
}
func (m *FixedQuadraticSegment) XXX_Size() int {
	return m.Size()
}
func (m *FixedQuadraticSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedQuadraticSegment.DiscardUnknown(m)
}

var xxx_messageInfo_FixedQuadraticSegment proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FixedQuadraticSegment)(nil), "escbackbone.ubcmm.FixedQuadraticSegment")
}

func init() {
	proto.RegisterFile("escbackbone/ubcmm/quadraticsegment.proto", fileDescriptor_d3b24765d5e913e2)
}

var fileDescriptor_d3b24765d5e913e2 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0x3f, 0x4b, 0xc3, 0x40,
	0x18, 0x06, 0xf0, 0x9c, 0xd5, 0x42, 0x03, 0x0e, 0x06, 0x85, 0xc3, 0xe1, 0x2a, 0x0e, 0xd2, 0x25,
	0xb9, 0x82, 0xab, 0x53, 0x91, 0xba, 0xb8, 0xf8, 0x67, 0x28, 0x6e, 0x77, 0x6f, 0x5e, 0xe2, 0xd1,
	0xe6, 0xae, 0xe6, 0x2e, 0x10, 0xbf, 0x85, 0xdf, 0xc9, 0xa5, 0x63, 0x47, 0x71, 0x28, 0x92, 0x7c,
	0x11, 0x49, 0x5a, 0x6b, 0xbb, 0x66, 0xba, 0x83, 0xf7, 0x79, 0x7e, 0xd3, 0xe3, 0x0f, 0xd0, 0x82,
	0x14, 0x30, 0x95, 0x46, 0x23, 0xcf, 0x25, 0xa4, 0x29, 0x7f, 0xcb, 0x45, 0x9c, 0x09, 0xa7, 0xc0,
	0x62, 0x92, 0xa2, 0x76, 0xd1, 0x3c, 0x33, 0xce, 0x04, 0x27, 0x3b, 0xc9, 0xa8, 0x49, 0x9e, 0x9f,
	0x26, 0x26, 0x31, 0xcd, 0x95, 0xd7, 0xbf, 0x75, 0xf0, 0xf2, 0xb3, 0xe3, 0x9f, 0x8d, 0x55, 0x81,
	0xf1, 0xc3, 0x1f, 0xf4, 0xb4, 0x86, 0x82, 0x1b, 0x9f, 0x08, 0x4a, 0x2e, 0xc8, 0xa0, 0x37, 0x8a,
	0x16, 0xab, 0xbe, 0xf7, 0xbd, 0xea, 0x5f, 0x25, 0xca, 0xbd, 0xe6, 0x32, 0x02, 0x93, 0x72, 0x30,
	0x36, 0x35, 0x76, 0xf3, 0x84, 0x36, 0x9e, 0x72, 0xf7, 0x3e, 0x47, 0x1b, 0xdd, 0x22, 0x3c, 0x12,
	0x51, 0xb7, 0x25, 0x3d, 0x68, 0xd7, 0x96, 0x75, 0x1b, 0x68, 0xa7, 0x5d, 0x1b, 0x82, 0x67, 0xff,
	0xd8, 0x82, 0x98, 0x29, 0x9d, 0x8c, 0x05, 0x38, 0x93, 0xd1, 0xc3, 0x56, 0xd2, 0x3e, 0x12, 0xdc,
	0xfb, 0x3d, 0xa5, 0x95, 0x53, 0x62, 0x36, 0x19, 0xd2, 0xa3, 0x56, 0xe2, 0x3f, 0x50, 0x6b, 0x90,
	0x67, 0x19, 0x6a, 0x37, 0x19, 0xd2, 0x6e, 0x3b, 0x6d, 0x0b, 0x8c, 0xee, 0x16, 0x25, 0x23, 0xcb,
	0x92, 0x91, 0x9f, 0x92, 0x91, 0x8f, 0x8a, 0x79, 0xcb, 0x8a, 0x79, 0x5f, 0x15, 0xf3, 0x5e, 0xc2,
	0x5d, 0x4c, 0x38, 0xd4, 0xa2, 0xe0, 0x68, 0x21, 0xdc, 0xce, 0xa8, 0xd8, 0x0c, 0xa9, 0x71, 0x65,
	0xb7, 0x59, 0xc5, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xa4, 0xfa, 0xd6, 0x6a, 0x02,
	0x00, 0x00,
}

func (m *FixedQuadraticSegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FixedQuadraticSegment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FixedQuadraticSegment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.CurrentX0.Size()
		i -= size
		if _, err := m.CurrentX0.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuadraticsegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.InitialX0.Size()
		i -= size
		if _, err := m.InitialX0.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuadraticsegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.ScalingFactor.Size()
		i -= size
		if _, err := m.ScalingFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuadraticsegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.C.Size()
		i -= size
		if _, err := m.C.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuadraticsegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.B.Size()
		i -= size
		if _, err := m.B.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuadraticsegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.A.Size()
		i -= size
		if _, err := m.A.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuadraticsegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuadraticsegment(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuadraticsegment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FixedQuadraticSegment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.A.Size()
	n += 1 + l + sovQuadraticsegment(uint64(l))
	l = m.B.Size()
	n += 1 + l + sovQuadraticsegment(uint64(l))
	l = m.C.Size()
	n += 1 + l + sovQuadraticsegment(uint64(l))
	l = m.ScalingFactor.Size()
	n += 1 + l + sovQuadraticsegment(uint64(l))
	l = m.InitialX0.Size()
	n += 1 + l + sovQuadraticsegment(uint64(l))
	l = m.CurrentX0.Size()
	n += 1 + l + sovQuadraticsegment(uint64(l))
	return n
}

func sovQuadraticsegment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuadraticsegment(x uint64) (n int) {
	return sovQuadraticsegment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FixedQuadraticSegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuadraticsegment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FixedQuadraticSegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FixedQuadraticSegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field A", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.A.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field B", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.B.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field C", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.C.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScalingFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ScalingFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialX0", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialX0.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentX0", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentX0.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuadraticsegment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuadraticsegment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuadraticsegment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuadraticsegment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuadraticsegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuadraticsegment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuadraticsegment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuadraticsegment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuadraticsegment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuadraticsegment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuadraticsegment = fmt.Errorf("proto: unexpected end of group")
)
