# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository at
# https://github.com/catenax-ng/product-esc-backbone-code
#
# SPDX-License-Identifier: Apache-2.0
version: 1

accounts:
- name: alice
  mnemonic: "rally exhaust blanket before trim level rebuild antique thunder
    over sphere matter hurt drop when foam much outside below donkey west entry
    advance earth"
  coins:
  - 200000000000000000000acax
  - 0uvoucher
- name: bob
  mnemonic: "mix thank switch crawl garden venue badge much kite foot clap
    stage skin shaft earn decade reward method ability mix lumber glad initial
    enrich"
  coins:
  - 100000000000000000000acax
  - 0uvoucher
- name: carol
  mnemonic: "defy soft media source say health kingdom define casual twin
    jacket spice mask skirt boat squirrel often pigeon lecture lawsuit little
    joke october lumber"
  coins:
  - 100000000000000000000acax
  - 0uvoucher
- name: test-wallet
  mnemonic: "old square lecture frog curtain habit bunker casino awesome defy
    fashion cry wife rain outer scene fork leaf raven twin hen hurt calm
    bulb"
  coins:
  - 10000000000000000000acax
  - 0uvoucher
- name: ubc_initiator
  mnemonic: "slice bachelor test little pink purse shaft weekend priority atom math borrow surprise undo trust pause drip payment gather gaze siren predict ostrich virus"
  coins:
  - 1000000acax
  - 100000000000000uvoucher

validators:
- name: alice
  bonded: 100000000000000000000acax

genesis:
  app_state:
    crisis:
      constant_fee:
        denom: acax
    gov:
      params:
        min_deposit:
        - amount: "100000000000000000000"
          denom: acax
    mint:
      params:
        mint_denom: acax
    staking:
      params:
        bond_denom: acax
build:
  main: "cmd/esc-backboned"
