// Copyright (c) 2022-2023 - for information on the respective copyright owner
// see the NOTICE file and/or the repository at
// https://github.com/catenax-ng/product-esc-backbone-code
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escbackbone/resourcesync/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a7e317ce1b34b3, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a7e317ce1b34b3, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetResourceMapRequest struct {
	Originator string `protobuf:"bytes,1,opt,name=originator,proto3" json:"originator,omitempty"`
	OrigResId  string `protobuf:"bytes,2,opt,name=origResId,proto3" json:"origResId,omitempty"`
}

func (m *QueryGetResourceMapRequest) Reset()         { *m = QueryGetResourceMapRequest{} }
func (m *QueryGetResourceMapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetResourceMapRequest) ProtoMessage()    {}
func (*QueryGetResourceMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a7e317ce1b34b3, []int{2}
}
func (m *QueryGetResourceMapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetResourceMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetResourceMapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetResourceMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetResourceMapRequest.Merge(m, src)
}
func (m *QueryGetResourceMapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetResourceMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetResourceMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetResourceMapRequest proto.InternalMessageInfo

func (m *QueryGetResourceMapRequest) GetOriginator() string {
	if m != nil {
		return m.Originator
	}
	return ""
}

func (m *QueryGetResourceMapRequest) GetOrigResId() string {
	if m != nil {
		return m.OrigResId
	}
	return ""
}

type QueryGetResourceMapResponse struct {
	ResourceMap ResourceMap `protobuf:"bytes,1,opt,name=resourceMap,proto3" json:"resourceMap"`
}

func (m *QueryGetResourceMapResponse) Reset()         { *m = QueryGetResourceMapResponse{} }
func (m *QueryGetResourceMapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetResourceMapResponse) ProtoMessage()    {}
func (*QueryGetResourceMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a7e317ce1b34b3, []int{3}
}
func (m *QueryGetResourceMapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetResourceMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetResourceMapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetResourceMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetResourceMapResponse.Merge(m, src)
}
func (m *QueryGetResourceMapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetResourceMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetResourceMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetResourceMapResponse proto.InternalMessageInfo

func (m *QueryGetResourceMapResponse) GetResourceMap() ResourceMap {
	if m != nil {
		return m.ResourceMap
	}
	return ResourceMap{}
}

type QueryAllResourceMapRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllResourceMapRequest) Reset()         { *m = QueryAllResourceMapRequest{} }
func (m *QueryAllResourceMapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllResourceMapRequest) ProtoMessage()    {}
func (*QueryAllResourceMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a7e317ce1b34b3, []int{4}
}
func (m *QueryAllResourceMapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllResourceMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllResourceMapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllResourceMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllResourceMapRequest.Merge(m, src)
}
func (m *QueryAllResourceMapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllResourceMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllResourceMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllResourceMapRequest proto.InternalMessageInfo

func (m *QueryAllResourceMapRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllResourceMapResponse struct {
	ResourceMap []ResourceMap       `protobuf:"bytes,1,rep,name=resourceMap,proto3" json:"resourceMap"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllResourceMapResponse) Reset()         { *m = QueryAllResourceMapResponse{} }
func (m *QueryAllResourceMapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllResourceMapResponse) ProtoMessage()    {}
func (*QueryAllResourceMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0a7e317ce1b34b3, []int{5}
}
func (m *QueryAllResourceMapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllResourceMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllResourceMapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllResourceMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllResourceMapResponse.Merge(m, src)
}
func (m *QueryAllResourceMapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllResourceMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllResourceMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllResourceMapResponse proto.InternalMessageInfo

func (m *QueryAllResourceMapResponse) GetResourceMap() []ResourceMap {
	if m != nil {
		return m.ResourceMap
	}
	return nil
}

func (m *QueryAllResourceMapResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "escbackbone.resourcesync.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "escbackbone.resourcesync.QueryParamsResponse")
	proto.RegisterType((*QueryGetResourceMapRequest)(nil), "escbackbone.resourcesync.QueryGetResourceMapRequest")
	proto.RegisterType((*QueryGetResourceMapResponse)(nil), "escbackbone.resourcesync.QueryGetResourceMapResponse")
	proto.RegisterType((*QueryAllResourceMapRequest)(nil), "escbackbone.resourcesync.QueryAllResourceMapRequest")
	proto.RegisterType((*QueryAllResourceMapResponse)(nil), "escbackbone.resourcesync.QueryAllResourceMapResponse")
}

func init() {
	proto.RegisterFile("escbackbone/resourcesync/query.proto", fileDescriptor_a0a7e317ce1b34b3)
}

var fileDescriptor_a0a7e317ce1b34b3 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6a, 0xd4, 0x40,
	0x18, 0xc7, 0x77, 0xd6, 0xba, 0xd0, 0x59, 0xf0, 0x30, 0xf6, 0xb0, 0xc4, 0x12, 0x4b, 0xb0, 0x56,
	0xad, 0x9d, 0x61, 0x6b, 0xc5, 0x9b, 0xd0, 0x1e, 0xac, 0x0a, 0x95, 0x35, 0xe0, 0xa5, 0x17, 0x99,
	0x64, 0x87, 0x18, 0xcc, 0x66, 0xd2, 0xcc, 0x44, 0xba, 0x48, 0x2f, 0x3e, 0x81, 0xe0, 0xc5, 0x67,
	0xf0, 0xae, 0xcf, 0xd0, 0x83, 0x87, 0x82, 0x17, 0x4f, 0x22, 0xbb, 0x3e, 0x88, 0xec, 0xcc, 0x94,
	0xcc, 0x6a, 0x62, 0xba, 0x78, 0xcb, 0x4c, 0xfe, 0xdf, 0xf7, 0xfd, 0xfe, 0x1f, 0xff, 0x04, 0xde,
	0x60, 0x22, 0x0c, 0x68, 0xf8, 0x3a, 0xe0, 0x29, 0x23, 0x39, 0x13, 0xbc, 0xc8, 0x43, 0x26, 0xc6,
	0x69, 0x48, 0x8e, 0x0a, 0x96, 0x8f, 0x71, 0x96, 0x73, 0xc9, 0x51, 0xcf, 0x52, 0x61, 0x5b, 0xe5,
	0xac, 0x44, 0x3c, 0xe2, 0x4a, 0x44, 0x66, 0x4f, 0x5a, 0xef, 0xac, 0x46, 0x9c, 0x47, 0x09, 0x23,
	0x34, 0x8b, 0x09, 0x4d, 0x53, 0x2e, 0xa9, 0x8c, 0x79, 0x2a, 0xcc, 0xdb, 0x3b, 0x21, 0x17, 0x23,
	0x2e, 0x48, 0x40, 0x05, 0xd3, 0x63, 0xc8, 0x9b, 0x7e, 0xc0, 0x24, 0xed, 0x93, 0x8c, 0x46, 0x71,
	0xaa, 0xc4, 0x46, 0xbb, 0x5e, 0xcb, 0x97, 0xd1, 0x9c, 0x8e, 0xce, 0x5b, 0x6e, 0xd6, 0xca, 0xce,
	0x0f, 0x2f, 0x47, 0x34, 0x33, 0xe2, 0x8d, 0x46, 0xb1, 0x11, 0xd6, 0x2f, 0x87, 0x16, 0xc3, 0x58,
	0x6a, 0x95, 0xb7, 0x02, 0xd1, 0xf3, 0x99, 0x89, 0x81, 0x02, 0xf2, 0xd9, 0x51, 0xc1, 0x84, 0xf4,
	0x5e, 0xc0, 0xab, 0x73, 0xb7, 0x22, 0xe3, 0xa9, 0x60, 0xe8, 0x21, 0xec, 0x68, 0xf0, 0x1e, 0x58,
	0x03, 0xb7, 0xba, 0xdb, 0x6b, 0xb8, 0x6e, 0xb5, 0x58, 0x57, 0xee, 0x2d, 0x9d, 0xfe, 0xb8, 0xde,
	0xf2, 0x4d, 0x95, 0x77, 0x08, 0x1d, 0xd5, 0x76, 0x9f, 0x49, 0xdf, 0x88, 0x0f, 0x68, 0x66, 0x86,
	0x22, 0x17, 0x42, 0x9e, 0xc7, 0x6a, 0x85, 0x3c, 0x57, 0x13, 0x96, 0x7d, 0xeb, 0x06, 0xad, 0xc2,
	0xe5, 0xd9, 0xc9, 0x67, 0xe2, 0xc9, 0xb0, 0xd7, 0x56, 0xaf, 0xcb, 0x0b, 0x2f, 0x81, 0xd7, 0x2a,
	0x7b, 0x1b, 0xf4, 0x03, 0xd8, 0xcd, 0xcb, 0x6b, 0xc3, 0xbf, 0x5e, 0xcf, 0x6f, 0xf5, 0x30, 0x26,
	0xec, 0x7a, 0x6f, 0x68, 0x9c, 0xec, 0x26, 0x49, 0x85, 0x93, 0x47, 0x10, 0x96, 0x59, 0x30, 0xb3,
	0x6e, 0x62, 0x1d, 0x1c, 0x3c, 0x0b, 0x0e, 0xd6, 0xf9, 0x34, 0xc1, 0xc1, 0x03, 0x1a, 0x31, 0x53,
	0xeb, 0x5b, 0x95, 0xde, 0x67, 0x60, 0x4c, 0xfd, 0x39, 0xa6, 0xce, 0xd4, 0xa5, 0xff, 0x31, 0x85,
	0xf6, 0xe7, 0xb0, 0xdb, 0x0a, 0x7b, 0xa3, 0x11, 0x5b, 0xb3, 0xd8, 0xdc, 0xdb, 0x9f, 0x96, 0xe0,
	0x65, 0xc5, 0x8d, 0x3e, 0x02, 0xd8, 0xd1, 0x51, 0x40, 0x77, 0xeb, 0xb9, 0xfe, 0x4e, 0xa0, 0xb3,
	0x75, 0x41, 0xb5, 0x9e, 0xee, 0xf5, 0xdf, 0x7d, 0xfb, 0xf5, 0xa1, 0xbd, 0x89, 0x6e, 0x93, 0x90,
	0x4a, 0x96, 0xd2, 0x63, 0xc2, 0x44, 0xb8, 0xf5, 0xaf, 0x6f, 0x0f, 0x7d, 0x05, 0xb0, 0x6b, 0x2d,
	0x04, 0xed, 0x34, 0x4c, 0xac, 0x0c, 0xad, 0x73, 0x7f, 0xc1, 0x2a, 0xc3, 0x3b, 0x50, 0xbc, 0x4f,
	0xd1, 0xe3, 0x0b, 0xf0, 0xda, 0x3f, 0x01, 0xf2, 0xb6, 0xfc, 0x20, 0x4e, 0xf4, 0x41, 0xc5, 0xff,
	0x04, 0x7d, 0x01, 0xf0, 0x8a, 0x35, 0x69, 0x37, 0x49, 0x1a, 0x1d, 0x55, 0x86, 0xb7, 0xd1, 0x51,
	0x75, 0x16, 0xbd, 0x07, 0xca, 0x51, 0x1f, 0x91, 0x05, 0x1d, 0xed, 0x3d, 0x3b, 0x9d, 0xb8, 0xe0,
	0x6c, 0xe2, 0x82, 0x9f, 0x13, 0x17, 0xbc, 0x9f, 0xba, 0xad, 0xb3, 0xa9, 0xdb, 0xfa, 0x3e, 0x75,
	0x5b, 0x87, 0x3b, 0x51, 0x2c, 0x5f, 0x15, 0x01, 0x0e, 0xf9, 0xa8, 0xba, 0xe9, 0xf1, 0x7c, 0x5b,
	0x39, 0xce, 0x98, 0x08, 0x3a, 0xea, 0xc7, 0x76, 0xef, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59,
	0xb7, 0xd8, 0xcd, 0x1d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ResourceMap items.
	ResourceMap(ctx context.Context, in *QueryGetResourceMapRequest, opts ...grpc.CallOption) (*QueryGetResourceMapResponse, error)
	ResourceMapAll(ctx context.Context, in *QueryAllResourceMapRequest, opts ...grpc.CallOption) (*QueryAllResourceMapResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/escbackbone.resourcesync.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ResourceMap(ctx context.Context, in *QueryGetResourceMapRequest, opts ...grpc.CallOption) (*QueryGetResourceMapResponse, error) {
	out := new(QueryGetResourceMapResponse)
	err := c.cc.Invoke(ctx, "/escbackbone.resourcesync.Query/ResourceMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ResourceMapAll(ctx context.Context, in *QueryAllResourceMapRequest, opts ...grpc.CallOption) (*QueryAllResourceMapResponse, error) {
	out := new(QueryAllResourceMapResponse)
	err := c.cc.Invoke(ctx, "/escbackbone.resourcesync.Query/ResourceMapAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ResourceMap items.
	ResourceMap(context.Context, *QueryGetResourceMapRequest) (*QueryGetResourceMapResponse, error)
	ResourceMapAll(context.Context, *QueryAllResourceMapRequest) (*QueryAllResourceMapResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ResourceMap(ctx context.Context, req *QueryGetResourceMapRequest) (*QueryGetResourceMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceMap not implemented")
}
func (*UnimplementedQueryServer) ResourceMapAll(ctx context.Context, req *QueryAllResourceMapRequest) (*QueryAllResourceMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResourceMapAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escbackbone.resourcesync.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ResourceMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetResourceMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ResourceMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escbackbone.resourcesync.Query/ResourceMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ResourceMap(ctx, req.(*QueryGetResourceMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ResourceMapAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllResourceMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ResourceMapAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escbackbone.resourcesync.Query/ResourceMapAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ResourceMapAll(ctx, req.(*QueryAllResourceMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "escbackbone.resourcesync.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ResourceMap",
			Handler:    _Query_ResourceMap_Handler,
		},
		{
			MethodName: "ResourceMapAll",
			Handler:    _Query_ResourceMapAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "escbackbone/resourcesync/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetResourceMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetResourceMapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetResourceMapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OrigResId) > 0 {
		i -= len(m.OrigResId)
		copy(dAtA[i:], m.OrigResId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OrigResId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Originator) > 0 {
		i -= len(m.Originator)
		copy(dAtA[i:], m.Originator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Originator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetResourceMapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetResourceMapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetResourceMapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ResourceMap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllResourceMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllResourceMapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllResourceMapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllResourceMapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllResourceMapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllResourceMapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ResourceMap) > 0 {
		for iNdEx := len(m.ResourceMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ResourceMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetResourceMapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Originator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.OrigResId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetResourceMapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ResourceMap.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllResourceMapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllResourceMapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ResourceMap) > 0 {
		for _, e := range m.ResourceMap {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetResourceMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetResourceMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetResourceMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Originator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Originator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigResId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrigResId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetResourceMapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetResourceMapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetResourceMapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ResourceMap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllResourceMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllResourceMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllResourceMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllResourceMapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllResourceMapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllResourceMapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceMap = append(m.ResourceMap, ResourceMap{})
			if err := m.ResourceMap[len(m.ResourceMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
