abci = "socket"
db_backend = "goleveldb"
db_dir = "data"
fast_sync = true
filter_peers = false
genesis_file = "config/genesis.json"
log_format = "plain"
log_level = "info"
moniker = "n4"
node_key_file = "config/node_key.json"
priv_validator_key_file = "config/priv_validator_key.json"
priv_validator_laddr = ""
priv_validator_state_file = "data/priv_validator_state.json"
proxy_app = "tcp://127.0.0.1:26658"

[consensus]
  create_empty_blocks = true
  create_empty_blocks_interval = "0s"
  double_sign_check_height = 0.0
  peer_gossip_sleep_duration = "100ms"
  peer_query_maj23_sleep_duration = "2s"
  skip_timeout_commit = false
  timeout_commit = "5s"
  timeout_precommit = "1s"
  timeout_precommit_delta = "500ms"
  timeout_prevote = "1s"
  timeout_prevote_delta = "500ms"
  timeout_propose = "3s"
  timeout_propose_delta = "500ms"
  wal_file = "data/cs.wal/wal"

[fastsync]
  version = "v0"

[instrumentation]
  max_open_connections = 3.0
  namespace = "tendermint"
  prometheus = false
  prometheus_listen_addr = ":26660"

[mempool]
  broadcast = true
  cache_size = 10000.0
  keep-invalid-txs-in-cache = false
  max_batch_bytes = 0.0
  max_tx_bytes = 1048576.0
  max_txs_bytes = 1073741824.0
  recheck = true
  size = 5000.0
  wal_dir = ""

[p2p]
  addr_book_file = "config/addrbook.json"
  addr_book_strict = true
  allow_duplicate_ip = false
  dial_timeout = "3s"
  external_address = ""
  flush_throttle_timeout = "100ms"
  handshake_timeout = "20s"
  laddr = "tcp://0.0.0.0:26656"
  max_num_inbound_peers = 40.0
  max_num_outbound_peers = 10.0
  max_packet_msg_payload_size = 1024.0
  persistent_peers = "082b6528408c7b94fd95dc9a4d3009f79fd14dc0@testnet-esc-backbone-1-service:26656,416aa38e953d883e030ca39fedb497cd0051c1e3@testnet-esc-backbone-4-service:26656,6efef91e2d3ca57f71bb1a70af3fc9e862fb21dd@testnet-esc-backbone-3-service:26656,93cedc7bf15cad0d4cf185ba2ff8f30e19ab292d@testnet-esc-backbone-2-service:26656"
  persistent_peers_max_dial_period = "0s"
  pex = true
  private_peer_ids = ""
  recv_rate = 5120000.0
  seed_mode = false
  seeds = ""
  send_rate = 5120000.0
  unconditional_peer_ids = ""
  upnp = false

[rpc]
  cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]
  cors_allowed_methods = ["HEAD", "GET", "POST"]
  cors_allowed_origins = ["*"]
  experimental_close_on_slow_client = false
  experimental_subscription_buffer_size = 200.0
  experimental_websocket_write_buffer_size = 200.0
  grpc_laddr = ""
  grpc_max_open_connections = 900.0
  laddr = "tcp://0.0.0.0:26657"
  max_body_bytes = 1000000.0
  max_header_bytes = 1048576.0
  max_open_connections = 900.0
  max_subscription_clients = 100.0
  max_subscriptions_per_client = 5.0
  pprof_laddr = "localhost:6060"
  timeout_broadcast_tx_commit = "10s"
  tls_cert_file = ""
  tls_key_file = ""
  unsafe = false

[statesync]
  chunk_fetchers = "4"
  chunk_request_timeout = "10s"
  discovery_time = "15s"
  enable = false
  rpc_servers = ""
  temp_dir = ""
  trust_hash = ""
  trust_height = 0.0
  trust_period = "168h0m0s"

[tx_index]
  indexer = "kv"
