version: '3.8'

services:
  esc-chain-web:
    image: esc-web
    ports:
      - "80:80"
  esc-backbone-1:
    image: esc-backbone
    volumes:
      - chain1:/validator/chain
    ports:
      - "1317:1317"
      - "26656-26658:26656-26658"
    networks:
      validator:
        ipv4_address: 172.16.0.2
  esc-backbone-2:
    image: esc-backbone
    volumes:
      - chain2:/validator/chain
    ports:
      - "1318:1317"
      - "26756-26758:26656-26658"
    networks:
      validator:
        ipv4_address: 172.16.0.3
  esc-backbone-3:
    image: esc-backbone
    volumes:
      - chain3:/validator/chain
    ports:
      - "1319:1317"
      - "26856-26858:26656-26658"
    networks:
      validator:
        ipv4_address: 172.16.0.4
  esc-backbone-4:
    image: esc-backbone
    volumes:
      - chain4:/validator/chain
    ports:
      - "1320:1317"
      - "26956-26958:26656-26658"
    networks:
      validator:
        ipv4_address: 172.16.0.5
networks:
  validator:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1
volumes:  
  chain1:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'work/n1'
  chain2:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'work/n2'
  chain3:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'work/n3'
  chain4:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'work/n4'
