// Copyright (c) 2022-2023 - for information on the respective copyright owner
// see the NOTICE file and/or the repository at
// https://github.com/catenax-ng/product-esc-backbone-code
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escbackbone/ubc/fixedsegment.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Fixedsegment struct {
	S           *Segment                               `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	IntervalP0X github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=intervalP0X,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"intervalP0X"`
}

func (m *Fixedsegment) Reset()         { *m = Fixedsegment{} }
func (m *Fixedsegment) String() string { return proto.CompactTextString(m) }
func (*Fixedsegment) ProtoMessage()    {}
func (*Fixedsegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c3623b730322b1c, []int{0}
}
func (m *Fixedsegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fixedsegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fixedsegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fixedsegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fixedsegment.Merge(m, src)
}
func (m *Fixedsegment) XXX_Size() int {
	return m.Size()
}
func (m *Fixedsegment) XXX_DiscardUnknown() {
	xxx_messageInfo_Fixedsegment.DiscardUnknown(m)
}

var xxx_messageInfo_Fixedsegment proto.InternalMessageInfo

func (m *Fixedsegment) GetS() *Segment {
	if m != nil {
		return m.S
	}
	return nil
}

func init() {
	proto.RegisterType((*Fixedsegment)(nil), "escbackbone.ubc.Fixedsegment")
}

func init() {
	proto.RegisterFile("escbackbone/ubc/fixedsegment.proto", fileDescriptor_2c3623b730322b1c)
}

var fileDescriptor_2c3623b730322b1c = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0x2d, 0x4e, 0x4e,
	0x4a, 0x4c, 0xce, 0x4e, 0xca, 0xcf, 0x4b, 0xd5, 0x2f, 0x4d, 0x4a, 0xd6, 0x4f, 0xcb, 0xac, 0x48,
	0x4d, 0x29, 0x4e, 0x4d, 0xcf, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x47, 0x52, 0xa3, 0x57, 0x9a, 0x94, 0x2c, 0x25, 0x8b, 0xae, 0x09, 0x45, 0xbd, 0x94, 0x48, 0x7a,
	0x7e, 0x7a, 0x3e, 0x98, 0xa9, 0x0f, 0x62, 0x41, 0x44, 0x95, 0x3a, 0x18, 0xb9, 0x78, 0xdc, 0x90,
	0x0c, 0x17, 0x52, 0xe3, 0x62, 0x2c, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd0, 0x43,
	0xb3, 0x42, 0x2f, 0x18, 0xa2, 0x28, 0x88, 0xb1, 0x58, 0x28, 0x80, 0x8b, 0x3b, 0x33, 0xaf, 0x24,
	0xb5, 0xa8, 0x2c, 0x31, 0x27, 0xc0, 0x20, 0x42, 0x82, 0x49, 0x81, 0x51, 0x83, 0xd3, 0x49, 0xef,
	0xc4, 0x3d, 0x79, 0x86, 0x5b, 0xf7, 0xe4, 0xd5, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92,
	0xf3, 0x73, 0xf5, 0x93, 0xf3, 0x8b, 0x73, 0xf3, 0x8b, 0xa1, 0x94, 0x6e, 0x71, 0x4a, 0xb6, 0x7e,
	0x49, 0x65, 0x41, 0x6a, 0xb1, 0x9e, 0x4b, 0x6a, 0x72, 0x10, 0xb2, 0x11, 0x4e, 0xae, 0x27, 0x1e,
	0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17,
	0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10, 0xa5, 0x8d, 0x6c, 0x5c, 0x62, 0x49, 0x6a, 0x5e,
	0x62, 0x85, 0x7e, 0x6a, 0x71, 0xb2, 0x2e, 0xdc, 0xb7, 0x15, 0x60, 0xff, 0x82, 0xcd, 0x4d, 0x62,
	0x03, 0x7b, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x46, 0xe4, 0x98, 0x32, 0x44, 0x01, 0x00,
	0x00,
}

func (m *Fixedsegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fixedsegment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fixedsegment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.IntervalP0X.Size()
		i -= size
		if _, err := m.IntervalP0X.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFixedsegment(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.S != nil {
		{
			size, err := m.S.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFixedsegment(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFixedsegment(dAtA []byte, offset int, v uint64) int {
	offset -= sovFixedsegment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Fixedsegment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.S != nil {
		l = m.S.Size()
		n += 1 + l + sovFixedsegment(uint64(l))
	}
	l = m.IntervalP0X.Size()
	n += 1 + l + sovFixedsegment(uint64(l))
	return n
}

func sovFixedsegment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFixedsegment(x uint64) (n int) {
	return sovFixedsegment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Fixedsegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFixedsegment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fixedsegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fixedsegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field S", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFixedsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFixedsegment
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFixedsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.S == nil {
				m.S = &Segment{}
			}
			if err := m.S.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntervalP0X", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFixedsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFixedsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFixedsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IntervalP0X.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFixedsegment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFixedsegment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFixedsegment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFixedsegment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFixedsegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFixedsegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFixedsegment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFixedsegment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFixedsegment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFixedsegment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFixedsegment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFixedsegment = fmt.Errorf("proto: unexpected end of group")
)
