// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escbackbone/ubc/flatsegment.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Flatsegment struct {
	Y  string `protobuf:"bytes,1,opt,name=y,proto3" json:"y,omitempty"`
	X0 string `protobuf:"bytes,2,opt,name=x0,proto3" json:"x0,omitempty"`
}

func (m *Flatsegment) Reset()         { *m = Flatsegment{} }
func (m *Flatsegment) String() string { return proto.CompactTextString(m) }
func (*Flatsegment) ProtoMessage()    {}
func (*Flatsegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9595e93b126ca8b, []int{0}
}
func (m *Flatsegment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Flatsegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Flatsegment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Flatsegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flatsegment.Merge(m, src)
}
func (m *Flatsegment) XXX_Size() int {
	return m.Size()
}
func (m *Flatsegment) XXX_DiscardUnknown() {
	xxx_messageInfo_Flatsegment.DiscardUnknown(m)
}

var xxx_messageInfo_Flatsegment proto.InternalMessageInfo

func (m *Flatsegment) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func (m *Flatsegment) GetX0() string {
	if m != nil {
		return m.X0
	}
	return ""
}

func init() {
	proto.RegisterType((*Flatsegment)(nil), "escbackbone.ubc.Flatsegment")
}

func init() { proto.RegisterFile("escbackbone/ubc/flatsegment.proto", fileDescriptor_b9595e93b126ca8b) }

var fileDescriptor_b9595e93b126ca8b = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0x2d, 0x4e, 0x4e,
	0x4a, 0x4c, 0xce, 0x4e, 0xca, 0xcf, 0x4b, 0xd5, 0x2f, 0x4d, 0x4a, 0xd6, 0x4f, 0xcb, 0x49, 0x2c,
	0x29, 0x4e, 0x4d, 0xcf, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x47,
	0x52, 0xa2, 0x57, 0x9a, 0x94, 0xac, 0xa4, 0xcd, 0xc5, 0xed, 0x86, 0x50, 0x25, 0xc4, 0xc3, 0xc5,
	0x58, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x58, 0x29, 0xc4, 0xc7, 0xc5, 0x54, 0x61,
	0x20, 0xc1, 0x04, 0xe6, 0x32, 0x55, 0x18, 0x38, 0xb9, 0x9e, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91,
	0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3,
	0xb1, 0x1c, 0x43, 0x94, 0x76, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e,
	0x72, 0x62, 0x49, 0x6a, 0x5e, 0x62, 0x85, 0x7e, 0x6a, 0x71, 0xb2, 0x2e, 0xdc, 0x39, 0x15, 0x60,
	0x07, 0x95, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0xdd, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xe4, 0xd9, 0x26, 0xb9, 0xb0, 0x00, 0x00, 0x00,
}

func (m *Flatsegment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Flatsegment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Flatsegment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.X0) > 0 {
		i -= len(m.X0)
		copy(dAtA[i:], m.X0)
		i = encodeVarintFlatsegment(dAtA, i, uint64(len(m.X0)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Y) > 0 {
		i -= len(m.Y)
		copy(dAtA[i:], m.Y)
		i = encodeVarintFlatsegment(dAtA, i, uint64(len(m.Y)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFlatsegment(dAtA []byte, offset int, v uint64) int {
	offset -= sovFlatsegment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Flatsegment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Y)
	if l > 0 {
		n += 1 + l + sovFlatsegment(uint64(l))
	}
	l = len(m.X0)
	if l > 0 {
		n += 1 + l + sovFlatsegment(uint64(l))
	}
	return n
}

func sovFlatsegment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFlatsegment(x uint64) (n int) {
	return sovFlatsegment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Flatsegment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFlatsegment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Flatsegment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Flatsegment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlatsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFlatsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFlatsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Y = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field X0", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFlatsegment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFlatsegment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFlatsegment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.X0 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFlatsegment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFlatsegment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFlatsegment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFlatsegment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFlatsegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFlatsegment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFlatsegment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFlatsegment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFlatsegment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFlatsegment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFlatsegment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFlatsegment = fmt.Errorf("proto: unexpected end of group")
)
