// Copyright (c) 2022-2023 - for information on the respective copyright owner
// see the NOTICE file and/or the repository at
// https://github.com/catenax-ng/product-esc-backbone-code
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: escbackbone/ubc/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgInit struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	RefTokenSupply  string `protobuf:"bytes,2,opt,name=refTokenSupply,proto3" json:"refTokenSupply,omitempty"`
	RefTokenPrice   string `protobuf:"bytes,3,opt,name=refTokenPrice,proto3" json:"refTokenPrice,omitempty"`
	RefProfitFactor string `protobuf:"bytes,4,opt,name=refProfitFactor,proto3" json:"refProfitFactor,omitempty"`
	BPool           string `protobuf:"bytes,5,opt,name=bPool,proto3" json:"bPool,omitempty"`
	BPoolUnder      string `protobuf:"bytes,6,opt,name=bPoolUnder,proto3" json:"bPoolUnder,omitempty"`
	SlopeP2         string `protobuf:"bytes,7,opt,name=slopeP2,proto3" json:"slopeP2,omitempty"`
	SlopeP3         string `protobuf:"bytes,8,opt,name=slopeP3,proto3" json:"slopeP3,omitempty"`
	FactorFy        string `protobuf:"bytes,9,opt,name=factorFy,proto3" json:"factorFy,omitempty"`
	FactorFxy       string `protobuf:"bytes,10,opt,name=factorFxy,proto3" json:"factorFxy,omitempty"`
}

func (m *MsgInit) Reset()         { *m = MsgInit{} }
func (m *MsgInit) String() string { return proto.CompactTextString(m) }
func (*MsgInit) ProtoMessage()    {}
func (*MsgInit) Descriptor() ([]byte, []int) {
	return fileDescriptor_615e99961022fa10, []int{0}
}
func (m *MsgInit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInit.Merge(m, src)
}
func (m *MsgInit) XXX_Size() int {
	return m.Size()
}
func (m *MsgInit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInit proto.InternalMessageInfo

func (m *MsgInit) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgInit) GetRefTokenSupply() string {
	if m != nil {
		return m.RefTokenSupply
	}
	return ""
}

func (m *MsgInit) GetRefTokenPrice() string {
	if m != nil {
		return m.RefTokenPrice
	}
	return ""
}

func (m *MsgInit) GetRefProfitFactor() string {
	if m != nil {
		return m.RefProfitFactor
	}
	return ""
}

func (m *MsgInit) GetBPool() string {
	if m != nil {
		return m.BPool
	}
	return ""
}

func (m *MsgInit) GetBPoolUnder() string {
	if m != nil {
		return m.BPoolUnder
	}
	return ""
}

func (m *MsgInit) GetSlopeP2() string {
	if m != nil {
		return m.SlopeP2
	}
	return ""
}

func (m *MsgInit) GetSlopeP3() string {
	if m != nil {
		return m.SlopeP3
	}
	return ""
}

func (m *MsgInit) GetFactorFy() string {
	if m != nil {
		return m.FactorFy
	}
	return ""
}

func (m *MsgInit) GetFactorFxy() string {
	if m != nil {
		return m.FactorFxy
	}
	return ""
}

type MsgInitResponse struct {
}

func (m *MsgInitResponse) Reset()         { *m = MsgInitResponse{} }
func (m *MsgInitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitResponse) ProtoMessage()    {}
func (*MsgInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_615e99961022fa10, []int{1}
}
func (m *MsgInitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitResponse.Merge(m, src)
}
func (m *MsgInitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitResponse proto.InternalMessageInfo

type MsgBuytokens struct {
	Buyer string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *MsgBuytokens) Reset()         { *m = MsgBuytokens{} }
func (m *MsgBuytokens) String() string { return proto.CompactTextString(m) }
func (*MsgBuytokens) ProtoMessage()    {}
func (*MsgBuytokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_615e99961022fa10, []int{2}
}
func (m *MsgBuytokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuytokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuytokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuytokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuytokens.Merge(m, src)
}
func (m *MsgBuytokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuytokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuytokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuytokens proto.InternalMessageInfo

func (m *MsgBuytokens) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgBuytokens) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MsgBuytokensResponse struct {
	Tokensbought  string `protobuf:"bytes,1,opt,name=tokensbought,proto3" json:"tokensbought,omitempty"`
	Vouchersspent string `protobuf:"bytes,2,opt,name=vouchersspent,proto3" json:"vouchersspent,omitempty"`
}

func (m *MsgBuytokensResponse) Reset()         { *m = MsgBuytokensResponse{} }
func (m *MsgBuytokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBuytokensResponse) ProtoMessage()    {}
func (*MsgBuytokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_615e99961022fa10, []int{3}
}
func (m *MsgBuytokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuytokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuytokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuytokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuytokensResponse.Merge(m, src)
}
func (m *MsgBuytokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuytokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuytokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuytokensResponse proto.InternalMessageInfo

func (m *MsgBuytokensResponse) GetTokensbought() string {
	if m != nil {
		return m.Tokensbought
	}
	return ""
}

func (m *MsgBuytokensResponse) GetVouchersspent() string {
	if m != nil {
		return m.Vouchersspent
	}
	return ""
}

type MsgSelltokens struct {
	Seller string `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *MsgSelltokens) Reset()         { *m = MsgSelltokens{} }
func (m *MsgSelltokens) String() string { return proto.CompactTextString(m) }
func (*MsgSelltokens) ProtoMessage()    {}
func (*MsgSelltokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_615e99961022fa10, []int{4}
}
func (m *MsgSelltokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSelltokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSelltokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSelltokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSelltokens.Merge(m, src)
}
func (m *MsgSelltokens) XXX_Size() int {
	return m.Size()
}
func (m *MsgSelltokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSelltokens.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSelltokens proto.InternalMessageInfo

func (m *MsgSelltokens) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *MsgSelltokens) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MsgSelltokensResponse struct {
	Tokenssold     string `protobuf:"bytes,1,opt,name=tokenssold,proto3" json:"tokenssold,omitempty"`
	Vouchersearned string `protobuf:"bytes,2,opt,name=vouchersearned,proto3" json:"vouchersearned,omitempty"`
}

func (m *MsgSelltokensResponse) Reset()         { *m = MsgSelltokensResponse{} }
func (m *MsgSelltokensResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSelltokensResponse) ProtoMessage()    {}
func (*MsgSelltokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_615e99961022fa10, []int{5}
}
func (m *MsgSelltokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSelltokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSelltokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSelltokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSelltokensResponse.Merge(m, src)
}
func (m *MsgSelltokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSelltokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSelltokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSelltokensResponse proto.InternalMessageInfo

func (m *MsgSelltokensResponse) GetTokenssold() string {
	if m != nil {
		return m.Tokenssold
	}
	return ""
}

func (m *MsgSelltokensResponse) GetVouchersearned() string {
	if m != nil {
		return m.Vouchersearned
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgInit)(nil), "escbackbone.ubc.MsgInit")
	proto.RegisterType((*MsgInitResponse)(nil), "escbackbone.ubc.MsgInitResponse")
	proto.RegisterType((*MsgBuytokens)(nil), "escbackbone.ubc.MsgBuytokens")
	proto.RegisterType((*MsgBuytokensResponse)(nil), "escbackbone.ubc.MsgBuytokensResponse")
	proto.RegisterType((*MsgSelltokens)(nil), "escbackbone.ubc.MsgSelltokens")
	proto.RegisterType((*MsgSelltokensResponse)(nil), "escbackbone.ubc.MsgSelltokensResponse")
}

func init() { proto.RegisterFile("escbackbone/ubc/tx.proto", fileDescriptor_615e99961022fa10) }

var fileDescriptor_615e99961022fa10 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xc7, 0xad, 0x7c, 0xd8, 0xf1, 0x90, 0xd4, 0x74, 0x49, 0xcb, 0x62, 0x5a, 0x11, 0x44, 0x1b,
	0x02, 0xa5, 0x32, 0xc4, 0xb7, 0x42, 0x2f, 0x86, 0x06, 0x7a, 0x30, 0xb8, 0x49, 0x7a, 0xe9, 0xa5,
	0x95, 0xd6, 0x63, 0xd9, 0x44, 0xd5, 0x8a, 0xfd, 0x08, 0xd6, 0x5b, 0xf4, 0x8d, 0x7a, 0xed, 0x31,
	0xc7, 0x1e, 0x8b, 0xfd, 0x06, 0x7d, 0x82, 0xa0, 0xd5, 0x4a, 0x96, 0x4c, 0x92, 0x9b, 0xfe, 0xbf,
	0xff, 0xec, 0xec, 0xcc, 0x68, 0x16, 0x28, 0x4a, 0x16, 0x06, 0xec, 0x26, 0xe4, 0x09, 0x0e, 0x74,
	0xc8, 0x06, 0x6a, 0xe9, 0xa7, 0x82, 0x2b, 0x4e, 0x7a, 0x35, 0xc7, 0xd7, 0x21, 0xf3, 0x7e, 0xef,
	0x40, 0x67, 0x2c, 0xa3, 0xcf, 0xc9, 0x42, 0x11, 0x0a, 0x1d, 0x26, 0x30, 0x50, 0x5c, 0x50, 0xe7,
	0xc4, 0x39, 0xeb, 0x5e, 0x96, 0x92, 0x9c, 0xc2, 0x33, 0x81, 0xb3, 0x6b, 0x7e, 0x83, 0xc9, 0x95,
	0x4e, 0xd3, 0x38, 0xa3, 0x3b, 0x26, 0x60, 0x8b, 0x92, 0x37, 0x70, 0x54, 0x92, 0x89, 0x58, 0x30,
	0xa4, 0xbb, 0x26, 0xac, 0x09, 0xc9, 0x19, 0xf4, 0x04, 0xce, 0x26, 0x82, 0xcf, 0x16, 0xea, 0x22,
	0x60, 0xf9, 0x7d, 0x7b, 0x26, 0x6e, 0x1b, 0x93, 0x63, 0xd8, 0x0f, 0x27, 0x9c, 0xc7, 0x74, 0xdf,
	0xf8, 0x85, 0x20, 0x2e, 0x80, 0xf9, 0xf8, 0x9a, 0x4c, 0x51, 0xd0, 0xb6, 0xb1, 0x6a, 0x24, 0xef,
	0x43, 0xc6, 0x3c, 0xc5, 0xc9, 0x39, 0xed, 0x14, 0x7d, 0x58, 0xb9, 0x71, 0x86, 0xf4, 0xa0, 0xee,
	0x0c, 0x49, 0x1f, 0x0e, 0x66, 0xe6, 0xce, 0x8b, 0x8c, 0x76, 0x8d, 0x55, 0x69, 0xf2, 0x0a, 0xba,
	0xf6, 0x7b, 0x99, 0x51, 0x30, 0xe6, 0x06, 0x78, 0xcf, 0xa1, 0x67, 0x07, 0x78, 0x89, 0x32, 0xe5,
	0x89, 0x44, 0xef, 0x03, 0x1c, 0x8e, 0x65, 0x34, 0xd2, 0x99, 0xca, 0x9b, 0x96, 0xa6, 0x0d, 0x9d,
	0x61, 0x39, 0xd6, 0x42, 0xe4, 0xf4, 0x36, 0x88, 0x35, 0xda, 0x59, 0x16, 0xc2, 0xfb, 0x01, 0xc7,
	0xf5, 0xb3, 0x65, 0x4e, 0xe2, 0xc1, 0x61, 0x41, 0x42, 0xae, 0xa3, 0xb9, 0xb2, 0xa9, 0x1a, 0x2c,
	0x1f, 0xff, 0x2d, 0xd7, 0x6c, 0x8e, 0x42, 0xca, 0x14, 0x13, 0x65, 0x33, 0x37, 0xa1, 0xf7, 0x11,
	0x8e, 0xc6, 0x32, 0xba, 0xc2, 0x38, 0xb6, 0xe5, 0xbd, 0x84, 0xb6, 0xc4, 0x38, 0xae, 0xea, 0xb3,
	0xea, 0x91, 0x02, 0xbf, 0xc3, 0x8b, 0xc6, 0xf1, 0xaa, 0x42, 0x17, 0xa0, 0x20, 0x92, 0xc7, 0x53,
	0x9b, 0xaa, 0x46, 0xf2, 0x25, 0x2a, 0x0b, 0xc1, 0x40, 0x24, 0x38, 0x2d, 0x97, 0xa8, 0x49, 0xcf,
	0xff, 0x3b, 0xb0, 0x3b, 0x96, 0x11, 0x19, 0xc1, 0x5e, 0xb1, 0x96, 0xfe, 0xd6, 0xd2, 0xfa, 0x76,
	0xde, 0xfd, 0x93, 0xc7, 0x9c, 0xaa, 0xa6, 0x2f, 0xd0, 0xdd, 0xfc, 0x86, 0xd7, 0x0f, 0x85, 0x57,
	0x76, 0xff, 0xed, 0x93, 0x76, 0x95, 0xf2, 0x1a, 0xa0, 0x36, 0x3b, 0xf7, 0xa1, 0x43, 0x1b, 0xbf,
	0x7f, 0xfa, 0xb4, 0x5f, 0x66, 0x1d, 0x7d, 0xfa, 0xb3, 0x72, 0x9d, 0xbb, 0x95, 0xeb, 0xfc, 0x5b,
	0xb9, 0xce, 0xaf, 0xb5, 0xdb, 0xba, 0x5b, 0xbb, 0xad, 0xbf, 0x6b, 0xb7, 0xf5, 0xed, 0x5d, 0xb4,
	0x50, 0x73, 0x1d, 0xfa, 0x8c, 0xff, 0x1c, 0xb0, 0x40, 0x61, 0x12, 0x2c, 0x07, 0x28, 0xd9, 0xfb,
	0xea, 0x81, 0x2f, 0x8b, 0x27, 0x9e, 0xa5, 0x28, 0xc3, 0xb6, 0x79, 0xe6, 0xc3, 0xfb, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x70, 0xed, 0xaa, 0x43, 0x02, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	Init(ctx context.Context, in *MsgInit, opts ...grpc.CallOption) (*MsgInitResponse, error)
	Buytokens(ctx context.Context, in *MsgBuytokens, opts ...grpc.CallOption) (*MsgBuytokensResponse, error)
	Selltokens(ctx context.Context, in *MsgSelltokens, opts ...grpc.CallOption) (*MsgSelltokensResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Init(ctx context.Context, in *MsgInit, opts ...grpc.CallOption) (*MsgInitResponse, error) {
	out := new(MsgInitResponse)
	err := c.cc.Invoke(ctx, "/escbackbone.ubc.Msg/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Buytokens(ctx context.Context, in *MsgBuytokens, opts ...grpc.CallOption) (*MsgBuytokensResponse, error) {
	out := new(MsgBuytokensResponse)
	err := c.cc.Invoke(ctx, "/escbackbone.ubc.Msg/Buytokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Selltokens(ctx context.Context, in *MsgSelltokens, opts ...grpc.CallOption) (*MsgSelltokensResponse, error) {
	out := new(MsgSelltokensResponse)
	err := c.cc.Invoke(ctx, "/escbackbone.ubc.Msg/Selltokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	Init(context.Context, *MsgInit) (*MsgInitResponse, error)
	Buytokens(context.Context, *MsgBuytokens) (*MsgBuytokensResponse, error)
	Selltokens(context.Context, *MsgSelltokens) (*MsgSelltokensResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Init(ctx context.Context, req *MsgInit) (*MsgInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedMsgServer) Buytokens(ctx context.Context, req *MsgBuytokens) (*MsgBuytokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buytokens not implemented")
}
func (*UnimplementedMsgServer) Selltokens(ctx context.Context, req *MsgSelltokens) (*MsgSelltokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Selltokens not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escbackbone.ubc.Msg/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Init(ctx, req.(*MsgInit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Buytokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuytokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Buytokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escbackbone.ubc.Msg/Buytokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Buytokens(ctx, req.(*MsgBuytokens))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Selltokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSelltokens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Selltokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/escbackbone.ubc.Msg/Selltokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Selltokens(ctx, req.(*MsgSelltokens))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "escbackbone.ubc.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Msg_Init_Handler,
		},
		{
			MethodName: "Buytokens",
			Handler:    _Msg_Buytokens_Handler,
		},
		{
			MethodName: "Selltokens",
			Handler:    _Msg_Selltokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "escbackbone/ubc/tx.proto",
}

func (m *MsgInit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FactorFxy) > 0 {
		i -= len(m.FactorFxy)
		copy(dAtA[i:], m.FactorFxy)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FactorFxy)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.FactorFy) > 0 {
		i -= len(m.FactorFy)
		copy(dAtA[i:], m.FactorFy)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FactorFy)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.SlopeP3) > 0 {
		i -= len(m.SlopeP3)
		copy(dAtA[i:], m.SlopeP3)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SlopeP3)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SlopeP2) > 0 {
		i -= len(m.SlopeP2)
		copy(dAtA[i:], m.SlopeP2)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SlopeP2)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BPoolUnder) > 0 {
		i -= len(m.BPoolUnder)
		copy(dAtA[i:], m.BPoolUnder)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BPoolUnder)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BPool) > 0 {
		i -= len(m.BPool)
		copy(dAtA[i:], m.BPool)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BPool)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RefProfitFactor) > 0 {
		i -= len(m.RefProfitFactor)
		copy(dAtA[i:], m.RefProfitFactor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RefProfitFactor)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RefTokenPrice) > 0 {
		i -= len(m.RefTokenPrice)
		copy(dAtA[i:], m.RefTokenPrice)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RefTokenPrice)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RefTokenSupply) > 0 {
		i -= len(m.RefTokenSupply)
		copy(dAtA[i:], m.RefTokenSupply)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RefTokenSupply)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgBuytokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuytokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuytokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuytokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuytokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuytokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vouchersspent) > 0 {
		i -= len(m.Vouchersspent)
		copy(dAtA[i:], m.Vouchersspent)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Vouchersspent)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tokensbought) > 0 {
		i -= len(m.Tokensbought)
		copy(dAtA[i:], m.Tokensbought)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tokensbought)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSelltokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSelltokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSelltokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSelltokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSelltokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSelltokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Vouchersearned) > 0 {
		i -= len(m.Vouchersearned)
		copy(dAtA[i:], m.Vouchersearned)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Vouchersearned)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tokenssold) > 0 {
		i -= len(m.Tokenssold)
		copy(dAtA[i:], m.Tokenssold)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tokenssold)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RefTokenSupply)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RefTokenPrice)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RefProfitFactor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BPool)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BPoolUnder)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SlopeP2)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SlopeP3)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FactorFy)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FactorFxy)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgBuytokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBuytokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tokensbought)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Vouchersspent)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSelltokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSelltokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tokenssold)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Vouchersearned)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefTokenSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefTokenSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefTokenPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefTokenPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefProfitFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefProfitFactor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BPool", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BPool = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BPoolUnder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BPoolUnder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlopeP2", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlopeP2 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlopeP3", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlopeP3 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactorFy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FactorFy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FactorFxy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FactorFxy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuytokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuytokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuytokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuytokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuytokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuytokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokensbought", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokensbought = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vouchersspent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vouchersspent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSelltokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSelltokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSelltokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSelltokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSelltokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSelltokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokenssold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokenssold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vouchersearned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vouchersearned = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
