# Copyright (c) 2022-2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Run dash tool

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  check-3rd-party-licences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run dash for go project
        id: run-dash
        uses: eclipse-tractusx/sig-infra/.github/actions/run-dash@main
        with:
          dependencies_file: "DEPENDENCIES"
          dash_input: "./go.sum"
          dash_version: "1.1.0"
          fail_on_out_of_date: "false"
          fail_on_rejected: "true"
          fail_on_restricted: "false"

      - name: Run dash for web project
        id: run-dash-web
        uses: eclipse-tractusx/sig-infra/.github/actions/run-dash@main
        with:
          dependencies_file: "DEPENDENCIES_WEB"
          dash_input: "./web/package-lock.json"
          dash_version: "1.1.0"
          fail_on_out_of_date: "false"
          fail_on_rejected: "true"
          fail_on_restricted: "false"

