# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository at
# https://github.com/catenax-ng/product-esc-backbone-code
#
# SPDX-License-Identifier: Apache-2.0

name: ESC-Backbone Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

jobs:

  build-esc-backbone-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: esc-backbone-web
          - target: esc-backbone-node
          - target: esc-backbone-node-init
          - target: esc-backbone-orchestrator
          - target: ssh-client
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Metadata ${{ matrix.target }}
        id: esc_backbone_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/catenax-ng/${{ matrix.target }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=match,pattern=\d.\d.\d
            type=sha
      - name: Build the  ${{ matrix.target }} image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile
          target: ${{ matrix.target }}
          push: true
          tags: ${{ steps.esc_backbone_meta.outputs.tags }}
          labels: ${{ steps.esc_backbone_meta.outputs.labels }}
  build-esc-backbone-faucet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ESC-Backbone Docker Metadata
        id: esc_backbone_faucet_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/catenax-ng/catena-faucet
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=match,pattern=\d.\d.\d
            type=sha
      - name: Build the ESC-Backbone faucet Docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile-faucet
          target: esc-backbone-faucet
          push: true
          tags: ${{ steps.esc_backbone_faucet_meta.outputs.tags }}
          labels: ${{ steps.esc_backbone_faucet_meta.outputs.labels }}