# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository at
# https://github.com/catenax-ng/product-esc-backbone-code
#
# SPDX-License-Identifier: Apache-2.0

name: ESC-Backbone Docker Base Images CI

on:
  schedule:
    - cron: "23 5 * * 6"

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ESC-Backbone-Build-base Docker Metadata
        id: esc_backbone_build_base_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/catenax-ng/esc-backbone-build-base
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=match,pattern=\d.\d.\d
            type=sha
            type=raw,value=latest
      - name: Build the ESC-Backbone-Build-base Docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile-base
          target: esc-backbone-build-base
          push: true
          tags: ${{ steps.esc_backbone_build_base_meta.outputs.tags }}
          labels: ${{ steps.esc_backbone_build_base_meta.outputs.labels }}
      - name: ESC-Backbone-Web-Build-base Docker Metadata
        id: esc_backbone_web_build_base_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/catenax-ng/esc-backbone-web-build-base
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=match,pattern=\d.\d.\d
            type=sha
            type=raw,value=latest
      - name: Build the ESC-Backbone-Web-Build-base Docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/Dockerfile-base
          target: esc-backbone-web-build-base
          push: true
          tags: ${{ steps.esc_backbone_web_build_base_meta.outputs.tags }}
          labels: ${{ steps.esc_backbone_web_build_base_meta.outputs.labels }}
      - name: ESC-Backbone-Web-base Docker Metadata
        id: esc_backbone_web_base_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/catenax-ng/esc-backbone-web-base
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=match,pattern=\d.\d.\d
            type=sha
            type=raw,value=latest
      - name: Build the ESC-Backbone-Web-base Docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/Dockerfile-base
          target: esc-backbone-web-base
          push: true
          tags: ${{ steps.esc_backbone_web_base_meta.outputs.tags }}
          labels: ${{ steps.esc_backbone_web_base_meta.outputs.labels }}
      - name: ESC-Backbone-Debian-base Docker Metadata
        id: esc_backbone_debian_base_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/catenax-ng/esc-backbone-debian-base
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=match,pattern=\d.\d.\d
            type=sha
            type=raw,value=latest
      - name: Build the ESC-Backbone-Debian-base Docker image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: build/Dockerfile-base
          target: esc-backbone-debian-base
          push: true
          tags: ${{ steps.esc_backbone_debian_base_meta.outputs.tags }}
          labels: ${{ steps.esc_backbone_debian_base_meta.outputs.labels }}