# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository at
# https://github.com/catenax-ng/product-esc-backbone-code
#
# SPDX-License-Identifier: Apache-2.0

name: Golang tests

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - '*'

env:
  go-version: 1.19

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests for UBC module
        run: go test -timeout 60s -v -count=1 ./x/ubcmm/...

      - name: Benchmarks for UBC module
        run: go test -timeout 60s -v -count=1 ./x/ubcmm/... -bench=. -benchtime=2s -benchmem -run Bench
