# Copyright (c) 2022-2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository at
# https://github.com/catenax-ng/product-esc-backbone-code
#
# SPDX-License-Identifier: Apache-2.0

name: mid-term-demo Docker Image CI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-mid-term-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Mid Term Demo Metadata
        id: esc_mid_term_demo_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/catenax-ng/esc-mid-term-demo
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=match,pattern=\d.\d.\d
            type=sha
      - name: Build the mid-term-demo Docker image and push
        uses: docker/build-push-action@v2
        with:
          context: web-mid-term-demo/
          file: web-mid-term-demo/build/Dockerfile
          target: demo
          push: true
          tags: ${{ steps.esc_mid_term_demo_meta.outputs.tags }}
          labels: ${{ steps.esc_mid_term_demo_meta.outputs.labels }}